# Generated by Django 3.1.4 on 2021-01-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('bike_image', models.ImageField(upload_to='bike_images')),
                ('price_per_hr', models.IntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('fuel_capacity', models.IntegerField()),
                ('power', models.CharField(max_length=50)),
            ],
        ),
    ]
