# Generated by Django 2.2 on 2020-05-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rented_Bikes',
        ),
    ]
