# Generated by Django 3.1.4 on 2021-01-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bikes',
            new_name='Bike',
        ),
    ]
