# Generated by Django 3.1.4 on 2021-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210105_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='availability',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
