# Generated by Django 2.2 on 2020-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rented_bikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_bikes',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
