# Generated by Django 2.2 on 2020-06-04 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_extra_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_charges',
            name='Deluxe',
        ),
        migrations.RemoveField(
            model_name='extra_charges',
            name='Passion_Pro',
        ),
        migrations.RemoveField(
            model_name='extra_charges',
            name='Pleasure',
        ),
        migrations.RemoveField(
            model_name='extra_charges',
            name='Royal_Enfield_200CC',
        ),
        migrations.RemoveField(
            model_name='extra_charges',
            name='Splendor_Plus',
        ),
    ]
