# Generated by Django 2.2 on 2020-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200604_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='extra_charges',
        ),
    ]
